version: "3.8"
services:
  pgadmin4:
    image: dpage/pgadmin4
    container_name: my_pgadmin
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@admin.com
      - PGADMIN_DEFAULT_PASSWORD=admin
    ports:
      - "89:80"
    networks:
      - postgres-network
  postgres:
    image: postgres:14-alpine
    container_name: my_postgres
    environment:
      - POSTGRES_PASSWORD=postgres
    ports:
      - "5432:5432"
    networks:
      - postgres-network
    volumes:
      - /home/davi-edge/data/faculpg:/var/lib/postgresql/data
networks:
  postgres-network:
    driver: bridge